# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin.tracking:
        class: AppBundle\Admin\TrackingAdmin
        arguments: [~, AppBundle\Entity\Tracking, ~]
        tags:
            - { name: sonata.admin, group: "Tracking", manager_type: orm, label: Tracking }

    cron.export:
        class: AppBundle\Service\ExportCronService
        arguments: [ @doctrine.orm.entity_manager ]

    app.twig_extension:
        class: AppBundle\Service\TwigExtensionService
        public: false
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: twig.extension }

    kernel.listener.exception_listener:
        class: AppBundle\Service\ExceptionListener
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }