# src/OC/PlatformBundle/Resources/config/routing.yml

#app_home:
#    path:      /home
#    defaults:  { _controller: AppBundle:Home:index}



# redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/login
        permanent: true