# src/OC/PlatformBundle/Resources/config/routing.yml

app_home:
    path:      /q/{hash}
    defaults:  { _controller: AppBundle:Home:index}

app_merci:
    path:      /merci
    defaults:  { _controller: AppBundle:Home:merci}



# redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /merci
        permanent: true