# src/OC/PlatformBundle/Resources/config/routing.yml

app_desabo:
    path:      /desabo/{hash}
    defaults:  { _controller: AppBundle:Home:desabo}

# redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /not_fount
        permanent: true