<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TrackingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackingRepository extends \Doctrine\ORM\EntityRepository
{
	public function getSumsPerCampaign()
	{
		$qb = $this->createQueryBuilder('t')
			->select('t.idCampaignName')
			->addSelect('SUM(t.opens) opens')
			->addSelect('SUM(t.opensOnce) opensOnce')
			->addSelect('SUM(t.clics) clics')
			->addSelect('SUM(t.clicsOnce) clicsOnce')
			->addSelect('SUM(t.hardBounce) hardBounce')
			->addSelect('SUM(t.softBounce) softBounce')
			->addSelect('SUM(t.unsuscribe) unsuscribes')
			->groupBy('t.idCampaignName')
		;

		return $qb
			->getQuery()
			->getScalarResult();
			//->getResult();
	}
	
}